test_xml_file_path = "tests/lxml/data/example-cro.xml"
test_html_file_path = "tests/lxml/data/example.html"
test_xml_file_string = b'<ObrazacURA xmlns="none-ns-value" xmlns:meta="meta-ns-value" xmlns:xsi="xsi-ns-value" verzijaSheme="1.0" xsi:schemaLocation="none-ns-value ObrazacURA-v1-0.xsd">\n\t<meta:Metapodaci>\n\t\t<meta:Naslov dc="http://purl.org/dc/elements/1.1/title">Knjiga primljenih (ulaznih) ra&#269;una</meta:Naslov>\n\t\t<meta:Autor dc="http://purl.org/dc/elements/1.1/creator">IVAN HORVAT</meta:Autor>\n\t\t<meta:Datum dc="http://purl.org/dc/elements/1.1/date">2019-02-05T10:55:44</meta:Datum>\n\t\t<meta:Format dc="http://purl.org/dc/elements/1.1/format">text/xml</meta:Format>\n\t\t<meta:Jezik dc="http://purl.org/dc/elements/1.1/language">hr-HR</meta:Jezik>\n\t\t<meta:Identifikator dc="http://purl.org/dc/elements/1.1/identifier">d7716e91-71cd-46cc-beff-d703bfa98295</meta:Identifikator>\n\t\t<meta:Uskladjenost dc="http://purl.org/dc/terms/conformsTo">ObrazacURA-v1-0</meta:Uskladjenost>\n\t\t<meta:Tip dc="http://purl.org/dc/elements/1.1/type">Elektroni&#269;ki obrazac</meta:Tip>\n\t\t<meta:Adresant>Ministarstvo Financija, Porezna uprava, Zagreb</meta:Adresant>\n\t</meta:Metapodaci>\n\t<Zaglavlje>\n\t\t<Razdoblje>\n\t\t\t<DatumOd>2019-01-01</DatumOd>\n\t\t\t<DatumDo>2019-01-31</DatumDo>\n\t\t</Razdoblje>\n\t\t<Obveznik>\n\t\t\t<OIB>00000000001</OIB>\n\t\t\t<Naziv>Dobra tvrtka d.o.o.</Naziv>\n\t\t\t<Adresa>\n\t\t\t\t<Mjesto>Zagreb</Mjesto>\n\t\t\t\t<Ulica>Radni&#269;ka</Ulica>\n\t\t\t\t<Broj>1</Broj>\n\t\t\t\t<DodatakKucnomBroju>a</DodatakKucnomBroju>\n\t\t\t</Adresa>\n\t\t\t<PodrucjeDjelatnosti>A</PodrucjeDjelatnosti>\n\t\t\t<SifraDjelatnosti>0111</SifraDjelatnosti>\n\t\t</Obveznik>\n\t\t<ObracunSastavio>\n\t\t\t<Ime>Ivan</Ime>\n\t\t\t<Prezime>Horvat</Prezime>\n\t\t</ObracunSastavio>\n\t</Zaglavlje>\n\t<Tijelo>\n\t\t<Racuni>\n\t\t\t<R>\n\t\t\t\t<R1>1</R1>\n\t\t\t\t<R2>2354/1/1</R2>\n\t\t\t\t<R3>2019-01-05</R3>\n\t\t\t\t<R4>Ivan Horvat</R4>\n\t\t\t\t<R5>Ilica 1, Zagreb</R5>\n\t\t\t\t<R6>1</R6>\n\t\t\t\t<R7>10000000000</R7>\n\t\t\t\t<R8>0.00</R8>\n\t\t\t\t<R9>0.00</R9>\n\t\t\t\t<R10>0.00</R10>\n\t\t\t\t<R11>0.00</R11>\n\t\t\t\t<R12>0.00</R12>\n\t\t\t\t<R13>0.00</R13>\n\t\t\t\t<R14>0.00</R14>\n\t\t\t\t<R15>0.00</R15>\n\t\t\t\t<R16>0.00</R16>\n\t\t\t\t<R17>0.00</R17>\n\t\t\t\t<R18>0.00</R18>\n\t\t\t</R>\n\t\t</Racuni>\n\t\t<Ukupno>\n\t\t\t<U8>0.00</U8>\n\t\t\t<U9>0.00</U9>\n\t\t\t<U10>0.00</U10>\n\t\t\t<U11>0.00</U11>\n\t\t\t<U12>0.00</U12>\n\t\t\t<U13>0.00</U13>\n\t\t\t<U14>0.00</U14>\n\t\t\t<U15>0.00</U15>\n\t\t\t<U16>0.00</U16>\n\t\t\t<U17>0.00</U17>\n\t\t\t<U18>0.00</U18>\n\t\t</Ukupno>\n\t</Tijelo>\n</ObrazacURA>\n'
test_html_file_string = b'<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="utf-8"/>\n    <title>Mozilla logo title!</title>\n  </head>\n  <body>\n    <p>Paragraph</p>\n  </body>\n</html>\n'
test_xml_first_element_string = b'<meta:Naslov xmlns:meta="meta-ns-value" xmlns="none-ns-value" xmlns:xsi="xsi-ns-value" dc="http://purl.org/dc/elements/1.1/title">Knjiga primljenih (ulaznih) ra&#269;una</meta:Naslov>\n\t\t\n'
test_xml_root_descendants = [
    "ObrazacURA",
    "Metapodaci",
    "Naslov",
    "Autor",
    "Datum",
    "Format",
    "Jezik",
    "Identifikator",
    "Uskladjenost",
    "Tip",
    "Adresant",
    "Zaglavlje",
    "Razdoblje",
    "DatumOd",
    "DatumDo",
    "Obveznik",
    "OIB",
    "Naziv",
    "Adresa",
    "Mjesto",
    "Ulica",
    "Broj",
    "DodatakKucnomBroju",
    "PodrucjeDjelatnosti",
    "SifraDjelatnosti",
    "ObracunSastavio",
    "Ime",
    "Prezime",
    "Tijelo",
    "Racuni",
    "R",
    "R1",
    "R2",
    "R3",
    "R4",
    "R5",
    "R6",
    "R7",
    "R8",
    "R9",
    "R10",
    "R11",
    "R12",
    "R13",
    "R14",
    "R15",
    "R16",
    "R17",
    "R18",
    "Ukupno",
    "U8",
    "U9",
    "U10",
    "U11",
    "U12",
    "U13",
    "U14",
    "U15",
    "U16",
    "U17",
    "U18",
]

test_edges_file_path = "tests/networkx/data/edges.csv"
